on:
  pull_request:
    paths:
      - packages/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: corepack enable
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: yarn install
        
      - run: yarn build
      # TODO: Add --compact once we publish them to npm
      - run: yarn dlx pkg-pr-new publish --yarn './packages/**'